### ISSUE TITLE
Need help with discord-webhook

### ISSUE THREAD

**Issue by FeuSalamander** [tiredvekster/LiteAntiCheat#2]
Hi, I recently installed your plugin and it's very cool and I wanted to try the discord webhook system but when a player gets punished no message is sent in the discord channel
here is my config:
```
discord-webhook:
  enabled: false
  #Server Settings -> Integrations -> Webhooks -> New Webhook
  webhook-url: https://discord.com/api/webhooks/1147977105305518232/SeYZW69P4C_fF9mAbFfaIvNnoa3ts83pz2sJTj87FUTnPP92J5oWLXKE5EQpJkFua48Z
  send-violations:
    enabled: true
    message-cooldown: 2000
    message-format: '```%name% was flagged for %check% (%vio%/%max-vio%)```'
  send-punishments:
    enabled: true
    message-cooldown: 0
    message-format: '```%%name% was punished for %check%```'
```
Thank you for your future reply
